### ISSUE TITLE
Could you drop conda?

### ISSUE THREAD

**Issue by stela2502** [numba/numba-hatchery#9]
Annaconda has shifted to a paid licence. And therefore we must not use that any more (University).
Is there a way to install this without the conda part?

**Comment by esc** [comment]
@stela2502 thank you for asking about this. We can not remove the use of `conda` and the Anaconda channels as this is an integral part of our approach on how to build Numba and hence used in the numba-hatchery.

However, if you are in an academic setting, you should be ok. The Anaconda FAQ about pricing at:

https://www.anaconda.com/pricing/terms-of-service-faqs

states that:

```
Anaconda is free for all educational entities—even those with 200 or more employees or contractors—when used in a
 course curriculum, including teaching, learning, and researching, at accredited universities worldwide. 
```
